name: Strapi Deploy
on: workflow_dispatch
jobs:
  setup-reverse-proxy:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v4

      - name: Install SSH key
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST_NAME }}
          username: ${{ secrets.SSH_USER_NAME }}
          port: ${{ secrets.SSH_PORT }}

      - name: run
        run: ssh server -p ${{ secrets.SSH_PORT }} "echo 'hogefuga'"