name: Setup Docker and Reverse Proxy
on: workflow_dispatch
jobs:
  setup-docker-and-reverse-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker and Reverse Proxy in SSH
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST_NAME }}
          username: ${{ secrets.SSH_USER_NAME }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/repositories
            git clone github-yukimasaki:yukimasaki/reverse-proxy-kit.git
            cd reverse-proxy-kit
            chmod a+x docker-install.sh
            ./docker-install.sh
            docker network create reverse-proxy-network
            cd ~/repositories/reverse-proxy-kit/reverse_proxy